music/urls.py
from django.urls import path
from . import views

app_name = 'music'

urlpatterns = [
    path('', views.AlbumIndexView.as_view(), name='album_index'),
    path('album/<int:pk>/', views.AlbumDetailView.as_view(), name='album_detail'),
    path('album/create', views.AlbumCreateView.as_view(), name='album_create'),
    path('album/<int:pk>/delete/', views.AlbumDeleteView.as_view(), name='album_delete'),
    path('album/<int:pk>/update/', views.AlbumUpdateView.as_view(), name='album_update'),
    path('songs', views.SongListView.as_view(), name='song_index'),
    path('album/<int:pk>/favorite/', views.toggle_fav_album, name='toggle_fav_album'),
    path('song/<int:pk>/favorite/', views.toggle_fav_song, name='toggle_fav_song'),
    # path('song/<int:pk>/favorite', views. , name='favorite_song'),
    # path('song/<int:pk>/edit', views. , name='edit_song'),
    # path('song/<int:pk>/delete', views. , name='delete_song'),
]

music_library/urls.py
from django.contrib import admin
from django.urls import path, include
from music import views
from django.conf import settings
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
    # path('signup/', views.SignupView.as_view(), name='signup_user'),
    # path('login/', views.LoginView.as_view(), name='login_user'),
    path('signup/', views.signup_user, name='signup_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),

    path('albumsAPI', views.AlbumAPI.as_view(), name='album_api')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

music/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Album(models.Model):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=20)
    album_title = models.CharField(max_length=20)
    genre = models.CharField(max_length=20)
    album_logo = models.FileField()
    is_favorite = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('music:album_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.album_title + ' - ' + self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=20)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title + ' - ' + self.album.artist

music/forms.py
from django.contrib.auth.admin import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            'username', 'email', 'password'
        ]

music/views.py
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.shortcuts import render, redirect, get_object_or_404
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView, View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Album, Song
from .forms import UserForm

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import AlbumSerializer


# Create your views here.
class AlbumIndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'music/album_index.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        return Album.objects.filter().order_by('album_title')


class AlbumDetailView(LoginRequiredMixin, generic.DeleteView):
    model = Album
    template_name = 'music/album_detail.html'
    # context_object_name = 'album_detail'


class AlbumCreateView(LoginRequiredMixin, CreateView):
    model = Album
    template_name = 'music/album_form.html'
    fields = [
        'artist', 'album_title', 'genre', 'album_logo', 'is_favorite'
    ]

    # If the model requires User field that has to be fetched automatically,
    # then use the form_valid() function to manually set the user as request.user

    # If you want to redirect to a specific page other than the DetailView as specified in the
    # get_absolute_url() function, you can override that by changing success_url parameter


class AlbumDeleteView(LoginRequiredMixin, DeleteView):
    model = Album
    success_url = reverse_lazy('music:album_index')


class AlbumUpdateView(LoginRequiredMixin, UpdateView):
    model = Album
    template_name = 'music/album_form.html'
    fields = [
        'artist', 'album_title', 'genre', 'album_logo', 'is_favorite'
    ]


class SongListView(LoginRequiredMixin, generic.ListView):
    model = Song
    template_name = 'music/song_index.html'
    context_object_name = 'song_list'

    def get_queryset(self):
        return Song.objects.order_by('song_title')


class SignupView(CreateView):
    form_class = UserCreationForm
    template_name = 'music/signup_user.html'
    success_url = reverse_lazy('music:album_index')

    def post(self, request, *args, **kwargs):
        # form = self.form_class(request.POST)
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    password=request.POST['password1']
                )
                user.save()
                login(request, user)
                return redirect('music:album_index')
            except IntegrityError:
                return render(request, self.template_name, {
                    'form': self.form_class,
                    'error': 'Username already exists.'
                })
        else:
            return render(request, self.template_name, {
                'form': self.form_class,
                'error': 'Passwords didn\'t match..'
            })


class LoginView(CreateView):
    form_class = AuthenticationForm
    template_name = 'music/login_user.html'
    success_url = reverse_lazy('music:album_index')

    def post(self, request, *args, **kwargs):
        user_exists = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user_exists:
            login(request, user_exists)
            return redirect('music:album_index')
        else:
            return render(request, self.template_name, {
                'form': self.form_class,
                'error': 'User credentials invalid.'
            })


def toggle_fav_album(request, pk):
    album = get_object_or_404(Album, pk=pk)
    album.is_favorite = not album.is_favorite
    album.save()
    return redirect('music:album_index')


def toggle_fav_song(request, pk):
    song = get_object_or_404(Song, pk=pk)
    song.is_favorite = not song.is_favorite
    song.save()
    album_id = Album.objects.get(song=song).id
    return redirect('music:album_detail', album_id)


def signup_user(request):
    if request.method == 'GET':
        return render(request, 'music/signup_user.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(
                    username=request.POST['username'],
                    password=request.POST['password1']
                )
                login(request, user)
                return redirect('music:album_index')
            except IntegrityError:
                return render(request, 'music/signup_user.html', {'form':UserCreationForm(), 'error': 'Username already exists.'})
        else:
            return render(request, 'music/signup_user.html',
                          {'form': UserCreationForm(), 'error': 'Passwords didn\'t match.'})


def login_user(request):
    if request.method == 'GET':
        return render(request, 'music/login_user.html', {'form': AuthenticationForm()})
    else:
        user_exists = authenticate(
            request,
            username=request.POST['username'],
            password=request.POST['password']
        )
        if user_exists:
            login(request, user_exists)
            return redirect('music:album_index')
        else:
            return render(request, 'music/login_user.html', {'form': UserCreationForm(), 'error': 'User credentials invalid.'})


def logout_user(request):
    logout(request)
    return redirect('login_user')


class AlbumAPI(APIView):
    def get(self, request):
        albums = Album.objects.all()
        serializer = AlbumSerializer(albums, many=True)
        return Response(serializer.data)

    def post(self, request):
        pass

music/templates/music/album_confirm_delete.html
{% extends 'music/base.html' %}
{% block content %}
{% load static %}

<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group border p-3 m-3">
            <h1 class="border-bottom mb-4 display-4">Album Details</h1>
            <h1 class="border-bottom mb-4 display-4">Are you are sure you want to delete <b>{{ object.album_title }}?</b></h1>
            {{ form.as_p }}
            <button class="btn btn-outline-danger" type="submit">Delete</button>
            <a class="btn btn-outline-secondary" href="{% url 'music:album_index' %}">Cancel</a>
        </div>
    </form>
</div>

{% endblock %}

music/templates/music/album_detail.html
{% extends 'music/base.html' %}
{% block content %}
{% load static %}

<div class="container-fluid m-3">
    <div class="row">
        <div class="col col-4 ml-3 border">
            <div class="card">
                <img src="{{ album.album_logo.url }}" class="card-image-top img-responsive" width="100%" height="100%">
                <div class="card-header text-center">
                    <strong>{{ album.album_title }}</strong>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Artist: {{ album.artist }} <br>
                        Genre: {{ album.genre }} <br>
                        Songs: {{ album.song_set.count }}
                    </p>
                </div>
                <div class="card-footer">
                    <div class="btn-group-horizontal">
                        <a href="{% url 'music:album_update' album.id %}" class="btn btn-outline-warning"><i class="fas fa-pen"></i></a>
                        <a href="{% url 'music:album_delete' album.id %}" class="btn btn-outline-danger"><i class="fas fa-trash"></i></a>
                        {% if album.is_favorite %}
                            <a href="{% url 'music:toggle_fav_album' album.id %}" class="btn btn-outline-success"><i class="fas fa-star"></i></a>
                        {% else %}
                            <a href="{% url 'music:toggle_fav_album' album.id %}" class="btn btn-outline-success"><i class="far fa-star"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-4 bg-dark text-light">
            <div class="row">
                <h1 class="display-4 text-center">Songs</h1>
            </div>
            {% for song in album.song_set.all %}
                <div class="row m-1 p-1 border-bottom">
                    <div class="col col-1">
                        {% if song.is_favorite %}
                            <a href="{% url 'music:toggle_fav_song' song.id %}" class="btn btn-outline-success btn-sm"><i class="fas fa-star"></i></a>
                        {% else %}
                            <a href="{% url 'music:toggle_fav_song' song.id %}" class="btn btn-outline-success btn-sm"><i class="far fa-star"></i></a>
                        {% endif %}
                    </div>
                    <div class="col col-1">
                        <a href="" class="btn btn-success btn-sm"><i class="fas fa-play"></i></a>
                    </div>
                    <div class="col col-8">
                        {{ song.song_title }}
                    </div>
                    <div class="col col-1">
                        <a href="" class="btn btn-danger btn-sm"><i class="fas fa-minus-circle"></i></a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block content %}
{% load static %}

<div class="container bg-dark text-light">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group p-3 m-3">
            <h1 class="border-bottom mb-4 display-4">Album Details</h1>
            {{ form.as_p }}
            <button class="btn btn-outline-success" type="submit">Save</button>
            <a class="btn btn-outline-secondary" href="{% url 'music:album_index' %}">Discard</a>
        </div>
    </form>
</div>

{% endblock %}

music/templates/music/album_index.html
{% extends 'music/base.html' %}
{% block content %}
{% load static %}

<div class="container mt-3 p-1 bg-dark">
    <div class="card-columns">
        {% for album in album_list %}
            <div class="card p-1">
                <img src="{{ album.album_logo.url }}" class="card-image-top img-responsive" width="100%" height="250">
                <div class="card-header text-center">
                    <strong>{{ album.album_title }}</strong>
                </div>
                <div class="card-body">
                    <p class="card-text">
                        Artist: {{ album.artist }} <br>
                        Genre: {{ album.genre }} <br>
                        Songs: {{ album.song_set.count }}
                    </p>
                </div>
                <div class="card-footer">
                    <div class="btn-group-horizontal">
                        <a href="{% url 'music:album_detail' album.pk %}" class="btn btn-outline-info">View</a>
                        <a href="{% url 'music:album_update' album.id %}" class="btn btn-outline-warning"><i class="fas fa-pen"></i></a>
                        <a href="{% url 'music:album_delete' album.id %}" class="btn btn-outline-danger"><i class="fas fa-trash"></i></a>
                        {% if album.is_favorite %}
                            <a href="{% url 'music:toggle_fav_album' album.id %}" class="btn btn-outline-success"><i class="fas fa-star"></i></a>
                        {% else %}
                            <a href="{% url 'music:toggle_fav_album' album.id %}" class="btn btn-outline-success"><i class="far fa-star"></i></a>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
	{% load static %}
	<link rel="stylesheet" href="{% static 'music/style.css' %}" type="text/css">
</head>
<body>

<div class="container-fluid p-0 mb-1">
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<a class="navbar-brand" href="{% url 'music:album_index' %}">
			Viberr
		</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item ml-2">
					<a class="nav-link" href="{% url 'music:album_index' %}"><i class="fas fa-compact-disc"></i> Albums</a>
				</li>
				<li class="nav-item ml-2">
					<a class="nav-link" href="{% url 'music:song_index' %}"><i class="fas fa-music"></i> Songs</a>
				</li>
				<li class="nav-item ml-3">
					<a class="nav-link" href="{% url 'music:album_create' %}"><i class="fas fa-plus"></i> Add album</a>
				</li>
				<li class="nav-item mr-2">
					<form class="form-inline ml-3 navbar-nav" role="search" method="get" action="">
						<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
						<button class="btn btn-outline-light my-2 my-sm-0" type="submit"><i class="fas fa-search"></i></button>
					</form>
				</li>
			</ul>
			<ul class="navbar-nav">
				<li class="nav-item mr-2">
					{% if user.is_authenticated %}
						<strong class="text-light">Welcome	{{ user }}</strong>&emsp;
						<a class="btn btn-outline-light" href="{% url 'logout_user' %}"><i class="fas fa-power-off"></i> Logout</a>
					{% else %}
						<div class="btn-group">
							<a href="{% url 'login_user' %}" class="btn btn-outline-light"><i class="fas fa-sign-in-alt"></i> Login</a>
							<a href="{% url 'signup_user' %}" class="btn btn-outline-light"><i class="fas fa-user-plus"></i> Signup</a>
						</div>
					{% endif %}
				</li>
			</ul>
		</div>
	</nav>
</div>

{% block content %}{% endblock %}
</body>
</html>

music/templates/music/login_user.html
{% extends 'music/base.html' %}
{% block content %}

<div class="container">
    <h1 class="display-4">Login</h1>
    <hr>

    <p><strong>{{ error }}</strong></p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
        &emsp;Not a user <a href="{% url 'signup_user' %}">Sign Up</a>
    </form>
    <hr>
</div>

{% endblock %}

music/templates/music/signup_user.html
{% extends 'music/base.html' %}
{% block content %}

<div class="container">
    <h1 class="display-4">Sign Up</h1>
    <hr>

    <p><strong>{{ error }}</strong></p>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
        &emsp;Already a user <a href="{% url 'login_user' %}">Login</a>
    </form>
    <hr>
</div>

{% endblock %}

music/templates/music/song_index.html
{% extends 'music/base.html' %}
{% block content %}
{% load static %}

<div class="container mt-3">
    <div class="row m-1 p-1 border-bottom display-4">
        <div class="col col-1"></div>
        <div class="col col-5">
            Title
        </div>
        <div class="col col-3">
            Artist
        </div>
        <div class="col col-3">
            Album
        </div>
    </div>
    {% for song in song_list %}
        <div class="row m-1 p-1 border-bottom">
<!--            <div class="col col-1">-->
<!--                {% if song.is_favorite %}-->
<!--                    <a href="{% url 'music:toggle_fav_song' song.id %}" class="btn btn-outline-success btn-sm"><i class="fas fa-star"></i></a>-->
<!--                {% else %}-->
<!--                    <a href="{% url 'music:toggle_fav_song' song.id %}" class="btn btn-outline-success btn-sm"><i class="far fa-star"></i></a>-->
<!--                {% endif %}-->
<!--            </div>-->
            <div class="col col-1">
                <a href="" class="btn btn-success btn-sm"><i class="fas fa-play"></i></a>
            </div>
            <div class="col col-5">
                {{ song.song_title }}
            </div>
            <div class="col col-3">
                {{ song.album.artist }}
            </div>
            <div class="col col-3">
                {{ song.album.album_title }}
            </div>
<!--            <div class="col col-1">-->
<!--                <a href="" class="btn btn-danger btn-sm"><i class="fas fa-minus-circle"></i></a>-->
<!--            </div>-->
        </div>
    {% endfor %}
</div>

{% endblock %}